<?xml version="1.0" ?>
<robot name="roller_conveyor_40ft" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Parameters -->
    <xacro:property name="roller_diameter" value="0.050"/> <!-- 50.8mm -->
    <xacro:property name="roller_length" value="1.219"/>   <!-- 4ft -->
    <xacro:property name="conveyor_length" value="12.192"/> <!-- 5ft -->
    <xacro:property name="conveyor_width" value="1.219"/>  <!-- 4ft -->
    <xacro:property name="roller_count" value="128"/>
    <xacro:property name="roller_pitch" value="0.09525"/>
    <xacro:property name="pi" value="3.1415926"/>
    <xacro:property name="roller_spacing" value="${conveyor_length / (roller_count)}"/>

    <link name="base_footprint"/>
    <joint name="base_link" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>
    <!-- Base Frame -->
    <link name="base_link">
        <visual>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <geometry>
                <box size="12.192 1.219 0.1"/>
            </geometry>
            <material name="gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <geometry>
                <box size="12.192 1.219 0.1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <mass value="20.0"/>
            <inertia ixx="0.2" iyy="0.2" izz="0.2"/>
        </inertial>
    </link>

    <!-- Left Guide Frame-->
    <link name="leftFrame">
        <visual>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <geometry>
                <box size="12.192 0.05 0.5"/>
            </geometry>
            <material name="gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <geometry>
                <box size="12.192 0.05 0.5"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <mass value="20.0"/>
            <inertia ixx="0.2" iyy="0.2" izz="0.2"/>
        </inertial>
    </link>
    <joint name="leftFrameJoint" type="fixed">
        <parent link="base_link"/>
        <child link="leftFrame"/>
        <origin xyz="0 -0.63 0.2" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Right Guide Frame-->
    <link name="rightFrame">
        <visual>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <geometry>
                <box size="12.192 0.05 0.5"/>
            </geometry>
            <material name="gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <geometry>
                <box size="12.192 0.05 0.5"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="-6.096 0 0" rpy="0 0 0" />
            <mass value="20.0"/>
            <inertia ixx="0.2" iyy="0.2" izz="0.2"/>
        </inertial>
    </link>
    <joint name="rightFrameJoint" type="fixed">
        <parent link="base_link"/>
        <child link="rightFrame"/>
        <origin xyz="0 0.63 0.2" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>


    <!-- Start Roller Definitions -->
    <!-- In between rollers, starting from #1->#32 -->
    <!-- Roller 1 -->
    <link name="Roller_1"><visual><geometry><cylinder radius="0.025" length="1.219"/></geometry></visual>
        <visual>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
        </inertial>
    </link>

    <joint name="Roller_1_1_joint" type="continuous">
        <parent link="base_link"/>
        <child link="Roller_1"/>
        <origin xyz="-${roller_pitch/2} 0 0.15" rpy="1.570796 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="1.0" friction="0.0"/>
    </joint>

    <!-- Roller #2->#32 -->
    <xacro:macro name="roller1st5ft" params="rollerNum">
        <link name="Roller_${rollerNum}">
            <visual>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
                <material name="black">
                    <color rgba="0.1 0.1 0.1 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="2.0"/>
                <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
            </inertial>
        </link>

        <joint name="Roller_1_${rollerNum}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="Roller_${rollerNum}"/>
            <origin xyz="-${(rollerNum-1)*roller_pitch + roller_pitch/2} 0 0.15" rpy="${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="1.0" friction="0.0"/>
        </joint>
    </xacro:macro>

    <!-- In between rollers, starting from #33->#64 -->
    <!-- Roller #33 -->
    <link name="Roller_33"><visual><geometry><cylinder radius="0.025" length="1.219"/></geometry></visual>
        <visual>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
        </inertial>
    </link>

    <joint name="Roller_33_33_joint" type="continuous">
        <parent link="base_link"/>
        <child link="Roller_33"/>
        <origin xyz="-${(32)*roller_pitch + roller_pitch/2} 0 0.15" rpy="1.570796 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="1.0" friction="0.0"/>
    </joint>

    <!-- Roller #34->#64 -->
    <xacro:macro name="roller2nd5ft" params="rollerNum">
        <link name="Roller_${rollerNum}">
            <visual>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
                <material name="black">
                    <color rgba="0.1 0.1 0.1 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="2.0"/>
                <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
            </inertial>
        </link>

        <joint name="Roller_33_${rollerNum}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="Roller_${rollerNum}"/>
            <origin xyz="-${(rollerNum-1)*roller_pitch + roller_pitch/2} 0 0.15" rpy="${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="1.0" friction="0.0"/>
        </joint>
    </xacro:macro>

    <!-- In between rollders, starting from #65->#96 -->
    <!-- Roller #65 -->
    <link name="Roller_65"><visual><geometry><cylinder radius="0.025" length="1.219"/></geometry></visual>
        <visual>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
        </inertial>
    </link>

    <joint name="Roller_65_65_joint" type="continuous">
        <parent link="base_link"/>
        <child link="Roller_65"/>
        <origin xyz="-${(64)*roller_pitch + roller_pitch/2} 0 0.15" rpy="1.570796 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="1.0" friction="0.0"/>
    </joint>

    <!-- Roller #66->#96 -->
    <xacro:macro name="roller3rd5ft" params="rollerNum">
        <link name="Roller_${rollerNum}">
            <visual>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
                <material name="black">
                    <color rgba="0.1 0.1 0.1 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="2.0"/>
                <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
            </inertial>
        </link>

        <joint name="Roller_65_${rollerNum}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="Roller_${rollerNum}"/>
            <origin xyz="-${(rollerNum-1)*roller_pitch + roller_pitch/2} 0 0.15" rpy="${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="1.0" friction="0.0"/>
        </joint>
    </xacro:macro>

    <!-- In between rollders, starting from #97->#128 -->
    <!-- Roller #97 -->
    <link name="Roller_97"><visual><geometry><cylinder radius="0.025" length="1.219"/></geometry></visual>
        <visual>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.025" length="1.219"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
        </inertial>
    </link>

    <joint name="Roller_97_97_joint" type="continuous">
        <parent link="base_link"/>
        <child link="Roller_97"/>
        <origin xyz="-${(96)*roller_pitch + roller_pitch/2} 0 0.15" rpy="1.570796 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="1.0" friction="0.0"/>
    </joint>

    <!-- Roller #98->#128 -->
    <xacro:macro name="roller4th5ft" params="rollerNum">
        <link name="Roller_${rollerNum}">
            <visual>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
                <material name="black">
                    <color rgba="0.1 0.1 0.1 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.025" length="1.219"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="2.0"/>
                <inertia ixx="0.02" iyy="0.02" izz="0.02"/>
            </inertial>
        </link>

        <joint name="Roller_97_${rollerNum}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="Roller_${rollerNum}"/>
            <origin xyz="-${(rollerNum-1)*roller_pitch + roller_pitch/2} 0 0.15" rpy="${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="1.0" friction="0.0"/>
        </joint>
    </xacro:macro>

    <!-- Instantiate Rollers -->
    <!-- First 5ft #1 -> #32-->
    <xacro:roller1st5ft rollerNum="2"/>
    <xacro:roller1st5ft rollerNum="3"/>
    <xacro:roller1st5ft rollerNum="4"/>
    <xacro:roller1st5ft rollerNum="5"/>
    <xacro:roller1st5ft rollerNum="6"/>
    <xacro:roller1st5ft rollerNum="7"/>
    <xacro:roller1st5ft rollerNum="8"/>
    <xacro:roller1st5ft rollerNum="9"/>
    <xacro:roller1st5ft rollerNum="10"/>
    <xacro:roller1st5ft rollerNum="11"/>
    <xacro:roller1st5ft rollerNum="12"/>
    <xacro:roller1st5ft rollerNum="13"/>
    <xacro:roller1st5ft rollerNum="14"/>
    <xacro:roller1st5ft rollerNum="15"/>
    <xacro:roller1st5ft rollerNum="16"/>
    <xacro:roller1st5ft rollerNum="17"/>
    <xacro:roller1st5ft rollerNum="18"/>
    <xacro:roller1st5ft rollerNum="19"/>
    <xacro:roller1st5ft rollerNum="20"/>
    <xacro:roller1st5ft rollerNum="21"/>
    <xacro:roller1st5ft rollerNum="22"/>
    <xacro:roller1st5ft rollerNum="23"/>
    <xacro:roller1st5ft rollerNum="24"/>
    <xacro:roller1st5ft rollerNum="25"/>
    <xacro:roller1st5ft rollerNum="26"/>
    <xacro:roller1st5ft rollerNum="27"/>
    <xacro:roller1st5ft rollerNum="28"/>
    <xacro:roller1st5ft rollerNum="29"/>
    <xacro:roller1st5ft rollerNum="30"/>
    <xacro:roller1st5ft rollerNum="31"/>
    <xacro:roller1st5ft rollerNum="32"/>

    <!-- Second 5ft #33 -> #64-->
    <xacro:roller2nd5ft rollerNum="34"/>
    <xacro:roller2nd5ft rollerNum="35"/>
    <xacro:roller2nd5ft rollerNum="36"/>
    <xacro:roller2nd5ft rollerNum="37"/>
    <xacro:roller2nd5ft rollerNum="38"/>
    <xacro:roller2nd5ft rollerNum="39"/>
    <xacro:roller2nd5ft rollerNum="40"/>
    <xacro:roller2nd5ft rollerNum="41"/>
    <xacro:roller2nd5ft rollerNum="42"/>
    <xacro:roller2nd5ft rollerNum="43"/>
    <xacro:roller2nd5ft rollerNum="44"/>
    <xacro:roller2nd5ft rollerNum="45"/>
    <xacro:roller2nd5ft rollerNum="46"/>
    <xacro:roller2nd5ft rollerNum="47"/>
    <xacro:roller2nd5ft rollerNum="48"/>
    <xacro:roller2nd5ft rollerNum="49"/>
    <xacro:roller2nd5ft rollerNum="50"/>
    <xacro:roller2nd5ft rollerNum="51"/>
    <xacro:roller2nd5ft rollerNum="52"/>
    <xacro:roller2nd5ft rollerNum="53"/>
    <xacro:roller2nd5ft rollerNum="54"/>
    <xacro:roller2nd5ft rollerNum="55"/>
    <xacro:roller2nd5ft rollerNum="56"/>
    <xacro:roller2nd5ft rollerNum="57"/>
    <xacro:roller2nd5ft rollerNum="58"/>
    <xacro:roller2nd5ft rollerNum="59"/>
    <xacro:roller2nd5ft rollerNum="60"/>
    <xacro:roller2nd5ft rollerNum="61"/>
    <xacro:roller2nd5ft rollerNum="62"/>
    <xacro:roller2nd5ft rollerNum="63"/>
    <xacro:roller2nd5ft rollerNum="64"/>

    <!-- Third 5ft #65 -> #96-->
    <xacro:roller3rd5ft rollerNum="66"/>
    <xacro:roller3rd5ft rollerNum="67"/>
    <xacro:roller3rd5ft rollerNum="68"/>
    <xacro:roller3rd5ft rollerNum="69"/>
    <xacro:roller3rd5ft rollerNum="70"/>
    <xacro:roller3rd5ft rollerNum="71"/>
    <xacro:roller3rd5ft rollerNum="72"/>
    <xacro:roller3rd5ft rollerNum="73"/>
    <xacro:roller3rd5ft rollerNum="74"/>
    <xacro:roller3rd5ft rollerNum="75"/>
    <xacro:roller3rd5ft rollerNum="76"/>
    <xacro:roller3rd5ft rollerNum="77"/>
    <xacro:roller3rd5ft rollerNum="78"/>
    <xacro:roller3rd5ft rollerNum="79"/>
    <xacro:roller3rd5ft rollerNum="80"/>
    <xacro:roller3rd5ft rollerNum="81"/>
    <xacro:roller3rd5ft rollerNum="82"/>
    <xacro:roller3rd5ft rollerNum="83"/>
    <xacro:roller3rd5ft rollerNum="84"/>
    <xacro:roller3rd5ft rollerNum="85"/>
    <xacro:roller3rd5ft rollerNum="86"/>
    <xacro:roller3rd5ft rollerNum="87"/>
    <xacro:roller3rd5ft rollerNum="88"/>
    <xacro:roller3rd5ft rollerNum="89"/>
    <xacro:roller3rd5ft rollerNum="90"/>
    <xacro:roller3rd5ft rollerNum="91"/>
    <xacro:roller3rd5ft rollerNum="92"/>
    <xacro:roller3rd5ft rollerNum="93"/>
    <xacro:roller3rd5ft rollerNum="94"/>
    <xacro:roller3rd5ft rollerNum="95"/>
    <xacro:roller3rd5ft rollerNum="96"/>

    <!-- Fourth 5ft #97 -> #128-->
    <xacro:roller4th5ft rollerNum="98"/>
    <xacro:roller4th5ft rollerNum="99"/>
    <xacro:roller4th5ft rollerNum="100"/>
    <xacro:roller4th5ft rollerNum="101"/>
    <xacro:roller4th5ft rollerNum="102"/>
    <xacro:roller4th5ft rollerNum="103"/>
    <xacro:roller4th5ft rollerNum="104"/>
    <xacro:roller4th5ft rollerNum="105"/>
    <xacro:roller4th5ft rollerNum="106"/>
    <xacro:roller4th5ft rollerNum="107"/>
    <xacro:roller4th5ft rollerNum="108"/>
    <xacro:roller4th5ft rollerNum="109"/>
    <xacro:roller4th5ft rollerNum="110"/>
    <xacro:roller4th5ft rollerNum="111"/>
    <xacro:roller4th5ft rollerNum="112"/>
    <xacro:roller4th5ft rollerNum="113"/>
    <xacro:roller4th5ft rollerNum="114"/>
    <xacro:roller4th5ft rollerNum="115"/>
    <xacro:roller4th5ft rollerNum="116"/>
    <xacro:roller4th5ft rollerNum="117"/>
    <xacro:roller4th5ft rollerNum="118"/>
    <xacro:roller4th5ft rollerNum="119"/>
    <xacro:roller4th5ft rollerNum="120"/>
    <xacro:roller4th5ft rollerNum="121"/>
    <xacro:roller4th5ft rollerNum="122"/>
    <xacro:roller4th5ft rollerNum="123"/>
    <xacro:roller4th5ft rollerNum="124"/>
    <xacro:roller4th5ft rollerNum="125"/>
    <xacro:roller4th5ft rollerNum="126"/>
    <xacro:roller4th5ft rollerNum="127"/>
    <xacro:roller4th5ft rollerNum="128"/>








    

</robot>
